export const NOTIFICATION_CATEGORIES = {
  application_sent:      'application',
  application_approved:  'application',
  application_rejected:  'application',
  application_cancelled: 'application',
  new_application:       'application',

  group_created:            'group',
  group_activated:          'group',
  group_chat_opened:        'group',
  group_full:                'group',
  group_full_member:         'group',
  group_ended:               'group',
  group_cancelled:           'group',
  group_renewal:             'group',
  member_left:               'group',
  member_left_self:          'group',
  member_removed:            'group',
  member_confirmed_service:  'group',
  group_reviewed:            'group',
  service_review_reminder:   'group',

  fill_service_info:             'billing',
  service_info_filled:           'billing',
  credential_extraction_started: 'billing',
  credential_comment:            'billing',
  all_service_info_filled:       'billing',
  group_activation_expired:      'billing',
  service_info_deadline_passed:  'billing',
  escrow_released:               'billing',
  escrow_released_member:        'billing',
  upcoming_renewal:              'billing',
  billing_date_confirmed:        'billing',
  billing_date_adjusted:         'billing',
  payment_reminder:              'billing',
};

export const MUTABLE_NOTIFICATION_CATEGORY_KEYS = ['application', 'group', 'billing'];

export const ALWAYS_SEND_NOTIFICATION_TYPES = [
  'dispute_raised',
  'dispute_resolved',
  'dispute_resolved_by_host',
  'dispute_withdrawn',
  'dispute_escalated',
  'service_info_issue',
  'service_info_issue_resolved',
  'account_reactivated',
  'platform_report_resolved',
  'system',
];
